BEGIN;
CREATE TABLE tb_marca (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(120) NOT NULL UNIQUE,descricao VARCHAR(1000),ativo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE UNIQUE INDEX uk_marca_nome_normalizado ON tb_marca(lower(trim(nome)));
CREATE TABLE tb_categoria (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(120) NOT NULL,categoria_id BIGINT REFERENCES tb_categoria(id) ON DELETE RESTRICT,CONSTRAINT categoria_nao_autoreferencia CHECK(categoria_id IS NULL OR categoria_id<>id));
CREATE INDEX ix_categoria_pai ON tb_categoria(categoria_id);
CREATE TABLE tb_produto (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(160) NOT NULL,descricao TEXT,preco NUMERIC(12,2) NOT NULL CHECK(preco>0),quantidade_estoque INTEGER NOT NULL DEFAULT 0 CHECK(quantidade_estoque>=0),marca_id BIGINT NOT NULL REFERENCES tb_marca(id) ON DELETE RESTRICT,categoria_id BIGINT NOT NULL REFERENCES tb_categoria(id) ON DELETE RESTRICT,caminho_imagem VARCHAR(80));
CREATE INDEX ix_produto_marca ON tb_produto(marca_id);CREATE INDEX ix_produto_categoria ON tb_produto(categoria_id);
-- Serializa alterações da árvore também entre sessões/instâncias.
CREATE FUNCTION validar_arvore_categoria() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(72635421);
 IF NEW.categoria_id IS NOT NULL AND EXISTS (
  WITH RECURSIVE ancestrais AS (
   SELECT id,categoria_id FROM tb_categoria WHERE id=NEW.categoria_id
   UNION SELECT c.id,c.categoria_id FROM tb_categoria c JOIN ancestrais a ON c.id=a.categoria_id
  ) SELECT 1 FROM ancestrais WHERE id=NEW.id
 ) THEN RAISE EXCEPTION 'A hierarquia de categorias não permite ciclos'; END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER trg_categoria_sem_ciclo BEFORE INSERT OR UPDATE OF categoria_id ON tb_categoria FOR EACH ROW EXECUTE FUNCTION validar_arvore_categoria();
COMMIT;
